### PR TITLE
LPS-48609

### PR DESCRIPTION
**Pull request by marcellustavares**

### CODE REVIEW

**Comment by juangon** [comment]
Hi @pablocp, are there any updates on this? We need to add to a fixpack as soon as possible. BTW, why all that  <#else> condition if only adds "readonly='readonly'"?  Wouldn't be easier just to add a string variable for adding that?

Thanks very much!

/cc @marcellustavares

**Comment by dacousalr** [comment]
Hi @pablocp, I would like to know whether there are some updates on this, too. We have a customer that needs it.

Thanks in advance!

**Comment by pablocp** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by pablocp** [comment]
Pull request submitted to https://github.com/marcellustavares/liferay-portal/pull/419. <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
